language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

env:
  - # default environment without variables
  - COMPOSER_DEPENDENCIES_OPTIONS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer update --no-interaction --no-suggest --prefer-source ${COMPOSER_DEPENDENCIES_OPTIONS}

script:
  - bin/phing ci-build
