services:
    _defaults:
        autoconfigure: true
        autowire: false
        public: false

    VasekPurchart\RabbitMqConsumerHandlerBundle\Sleeper\Sleeper: ~

    vasek_purchart.rabbit_mq_consumer_handler.entity_manager: '@doctrine.orm.default_entity_manager'
